# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.89838498 0.84004253 0.13873679 ... 0.56024241 0.18543537 0.42074565]
 [0.74209656 0.9057675  0.97675381 ... 0.31261519 0.27195582 0.84258471]
 [0.77517886 0.6188388  0.31997616 ... 0.53283079 0.36150705 0.31884201]
 ...
 [0.74572171 0.9872878  0.64729817 ... 0.86288755 0.14425649 0.03273419]
 [0.54276458 0.8484285  0.02356849 ... 0.58700155 0.06337332 0.32543179]
 [0.90528638 0.98150606 0.14754746 ... 0.15759444 0.46948516 0.98604702]]
[[0.3379763  0.24643553 0.30401376 ... 0.90557436 0.93227489 0.05060462]
 [0.0556089  0.18030349 0.28696107 ... 0.56631572 0.55665323 0.73466817]
 [0.66011158 0.13861736 0.04966212 ... 0.98113772 0.30094483 0.83969801]
 ...
 [0.94021093 0.95043538 0.50623215 ... 0.69303803 0.18931783 0.25714836]
 [0.76378801 0.55896831 0.83561028 ... 0.51670958 0.49263949 0.31350228]
 [0.35810131 0.95459428 0.12868442 ... 0.21458781 0.22552292 0.20714039]]


Без использования numpy

In [ ]:
def mult(a, b):
    len(a)
    result = [[0 for j in range(len(b[0]))] for i in range(len(a))]

    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [ ]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 693 ms, sys: 0 ns, total: 693 ms
Wall time: 695 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.7 ms, sys: 86 µs, total: 1.78 ms
Wall time: 5.27 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5159429267441737e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.86827424 0.14766194 0.18000341] [0.19801094 0.31762118 0.982483  ]


In [ ]:
def scalar_product(a,b):
    s = sum(a[i] * b[i] for i in range(3))
    return s

In [ ]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 28 µs, sys: 4 µs, total: 32 µs
Wall time: 36.2 µs
CPU times: user 183 µs, sys: 0 ns, total: 183 µs
Wall time: 458 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы NumPy оказываются эффективнее благодаря использованию оптимизированных алгоритмов и функций, написанных на языке C. Кроме того, NumPy использует векторизацию, что позволяет выполнять операции над массивами данных более быстро, чем при использовании обычных циклов.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  if len(a) > 0 and len(a) == len(a[0]):
    diagonal_a = np.diagonal(a)
    even_elements = diagonal_a[diagonal_a % 2 == 0]
    return np.sum(even_elements)
  else:
    return 0

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[4, 1, 9, 3, 8],
       [8, 6, 6, 4, 8],
       [7, 9, 2, 6, 1],
       [3, 7, 3, 4, 4],
       [3, 6, 6, 4, 5]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 191 µs, sys: 21 µs, total: 212 µs
Wall time: 221 µs


16

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    cum_summ = np.cumsum(X, axis = 1)
    result = cum_summ / np.arange(1, X.shape[1] + 1)
    return result

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.92965881 0.73112673 0.17131436 0.95170186 0.42327251 0.22456702
 0.06151911 0.66106894 0.50730916 0.38013951 0.16085559 0.47002196
 0.36968719 0.68413484 0.36661613 0.80918428 0.68460202 0.08010264
 0.50751688 0.92659502 0.37403752 0.43459777 0.02541161 0.70721248
 0.56156415 0.07843261 0.23007104 0.37376275 0.76398883 0.72247036
 0.49045503 0.71047667 0.85762623 0.4670262  0.55565851 0.52045403
 0.67647073 0.1954106  0.15973827 0.11360216 0.51756531 0.3610486
 0.41045133 0.50337075 0.50911538 0.73861891 0.63085194 0.12527163
 0.56184773 0.74833598 0.00562522 0.72298461 0.01223765 0.32999483
 0.55756897 0.99392889 0.34733339 0.56208258 0.15019739 0.73603761
 0.9730646  0.97106561 0.88608188 0.3258886  0.06417847 0.02672053
 0.44400249 0.91141472 0.68514311 0.0684222  0.90874296 0.33928342
 0.16736665 0.05651731 0.31498114 0.0628372  0.50307458 0.85798557
 0.354665   0.02208074 0.30862098 0.03005122 0.10234508 0.58538589
 0.59160211 0.63078939 0.20819353 0.59120817 0.34405137 0.91057

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    elements = []
    count = []
    current_element = a[0]
    current_count = 1
    for i in range(1, len(a)):
      if a[i] == current_element:
        current_count += 1
      else:
        elements.append(a[i])
        count.append(current_count)
        current_element = a[i]
        current_count = 1
    result = np.array(elements), np.array(count)
    return result

In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 46 µs, sys: 0 ns, total: 46 µs
Wall time: 50.5 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
from types import new_class
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    new_X = X.copy()
    new_X[1::2] = a
    new_X[::2] = new_X[::2] ** 3
    reversed_new_X = new_X[::-1]
    result = np.concatenate((X, reversed_new_X))
    return result

In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 65 µs, sys: 6 µs, total: 71 µs
Wall time: 86.5 µs
